### ISSUE TITLE
Adding a "unmute and mute button" 

### ISSUE THREAD

**Issue by ChanMario** [anthonyfok/buzz-flash#13]
https://forums.adobe.com/thread/417625?start=0&tstart=0

The website above suggested serveral methods to create an unmute and mute button.

```ActionScript
var soundIsOn=true;
btn.addEventListener(MouseEvent.CLICK, changesound);
{
function changeSound(event:MouseEvent) {
  var st:SoundTransform = new SoundTransform();
  if (soundIsOn) {
   st.volume=0;
   SoundMixer.soundTransform=st;
   soundIsOn=false;
  } else {
   st.volume=1;
   SoundMixer.soundTransform=st;
   soundIsOn=true;
  }
}
};
```

I would like to know how to apply this script to create the button with unmute and mute button effect.
Please suggest how to do this. Thank you

**Comment by anthonyfok** [comment]
This is a really good YouTube video tutorial which I think we can use:

* [How to Make a Mute Button in Flash CS4 (AS3)](https://www.youtube.com/watch?v=Q2uXokbwUWA)

There is also another interesting YouTube video tutorial by mcvdigital that I hope we can use to solve the overlapping audio problem in Scene 4 (Buzz Lightyear’s Body Functions):

* [On/Off Sound buttons in Flash - NO ACTIONSCRIPTING!](https://www.youtube.com/watch?v=p5WklqV0No8)

**Comment by anthonyfok** [comment]
Awesome!  Mario followed the [How to Make a Mute Button in Flash CS4 (AS3)](https://www.youtube.com/watch?v=Q2uXokbwUWA) (https://www.youtube.com/watch?v=Q2uXokbwUWA) video tutorial and got it to work perfectly!

**Comment by anthonyfok** [comment]
Some trickery was used to workaround the Star Wars theme not playing, or later, the Mute/Unmute button not working when returning from Scene 2 or Scene 3.

It was resolved in time for the submission of the final project by the following tricks:

* Use Frame 1150, which the main loop (Frame 450 to 1149) never reaches, on Scene 1 to place a new instance of the Star Wars theme song to play there, reaching Frame 1150.
* Copy the related Mute/Unmute functions from Frame 1 to Frame 1150, but renamed relevant functions and variables, e.g. `Mute` got renamed to `Mute2`.
* In Scene 2 and Scene 3, upon clicking the "Home Button" or the "Coverpage Button", instead of using `gotoAndPlay(450,  "Scene 1");`, we use `gotoAndPlay(1150, "Scene 1"); instead.
* And finally, back on Frame 1150 of Scene 1, after the aforementioned mute/unmute functions setup, a final `gotoAndPlay(450)` jumps to the main loop.

And that is how we got both the Star Wars theme playing again, with the Mute/Unmute button working too, when a user returns to this "Home Page" (Scene 1 Main Loop) from Scene 2 or Scene 3.
